/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminCompetencyRouteImport } from './routes/admin.competency'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as TraineeIndexRouteImport } from './routes/trainee.index'
import { Route as TraineeAssessmentRouteImport } from './routes/trainee.assessment'
import { Route as TraineeCatalogRouteImport } from './routes/trainee.catalog'
import { Route as TraineeCertificatesRouteImport } from './routes/trainee.certificates'
import { Route as TraineeCoursesRouteImport } from './routes/trainee.courses'
import { Route as TraineeFeedbackRouteImport } from './routes/trainee.feedback'
import { Route as TraineeProfileRouteImport } from './routes/trainee.profile'
import { Route as TraineeResourceViewerRouteImport } from './routes/trainee.resource-viewer'
import { Route as TraineeResultsRouteImport } from './routes/trainee.results'
import { Route as TrainerIndexRouteImport } from './routes/trainer.index'
import { Route as TrainerCoursesRouteImport } from './routes/trainer.courses'
import { Route as TrainerLibraryRouteImport } from './routes/trainer.library'
import { Route as TrainerProfileRouteImport } from './routes/trainer.profile'
import { Route as TrainerQuestionnairesRouteImport } from './routes/trainer.questionnaires'
import { Route as TrainerTraineesRouteImport } from './routes/trainer.trainees'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/admin/announcements',
  path: '/admin/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/admin/billing',
  path: '/admin/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompetencyRoute = AdminCompetencyRouteImport.update({
  id: '/admin/competency',
  path: '/admin/competency',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/admin/courses',
  path: '/admin/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TraineeIndexRoute = TraineeIndexRouteImport.update({
  id: '/trainee/',
  path: '/trainee/',
  getParentRoute: () => rootRouteImport,
} as any)
const TraineeAssessmentRoute = TraineeAssessmentRouteImport.update({
  id: '/trainee/assessment',
  path: '/trainee/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const TraineeCatalogRoute = TraineeCatalogRouteImport.update({
  id: '/trainee/catalog',
  path: '/trainee/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const TraineeCertificatesRoute = TraineeCertificatesRouteImport.update({
  id: '/trainee/certificates',
  path: '/trainee/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const TraineeCoursesRoute = TraineeCoursesRouteImport.update({
  id: '/trainee/courses',
  path: '/trainee/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const TraineeFeedbackRoute = TraineeFeedbackRouteImport.update({
  id: '/trainee/feedback',
  path: '/trainee/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const TraineeProfileRoute = TraineeProfileRouteImport.update({
  id: '/trainee/profile',
  path: '/trainee/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TraineeResourceViewerRoute = TraineeResourceViewerRouteImport.update({
  id: '/trainee/resource-viewer',
  path: '/trainee/resource-viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const TraineeResultsRoute = TraineeResultsRouteImport.update({
  id: '/trainee/results',
  path: '/trainee/results',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerIndexRoute = TrainerIndexRouteImport.update({
  id: '/trainer/',
  path: '/trainer/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerCoursesRoute = TrainerCoursesRouteImport.update({
  id: '/trainer/courses',
  path: '/trainer/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerLibraryRoute = TrainerLibraryRouteImport.update({
  id: '/trainer/library',
  path: '/trainer/library',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerProfileRoute = TrainerProfileRouteImport.update({
  id: '/trainer/profile',
  path: '/trainer/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerQuestionnairesRoute = TrainerQuestionnairesRouteImport.update({
  id: '/trainer/questionnaires',
  path: '/trainer/questionnaires',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerTraineesRoute = TrainerTraineesRouteImport.update({
  id: '/trainer/trainees',
  path: '/trainer/trainees',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/competency': typeof AdminCompetencyRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/users': typeof AdminUsersRoute
  '/trainee/assessment': typeof TraineeAssessmentRoute
  '/trainee/catalog': typeof TraineeCatalogRoute
  '/trainee/certificates': typeof TraineeCertificatesRoute
  '/trainee/courses': typeof TraineeCoursesRoute
  '/trainee/feedback': typeof TraineeFeedbackRoute
  '/trainee/profile': typeof TraineeProfileRoute
  '/trainee/resource-viewer': typeof TraineeResourceViewerRoute
  '/trainee/results': typeof TraineeResultsRoute
  '/trainer/courses': typeof TrainerCoursesRoute
  '/trainer/library': typeof TrainerLibraryRoute
  '/trainer/profile': typeof TrainerProfileRoute
  '/trainer/questionnaires': typeof TrainerQuestionnairesRoute
  '/trainer/trainees': typeof TrainerTraineesRoute
  '/admin/': typeof AdminIndexRoute
  '/trainee/': typeof TraineeIndexRoute
  '/trainer/': typeof TrainerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/competency': typeof AdminCompetencyRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/users': typeof AdminUsersRoute
  '/trainee/assessment': typeof TraineeAssessmentRoute
  '/trainee/catalog': typeof TraineeCatalogRoute
  '/trainee/certificates': typeof TraineeCertificatesRoute
  '/trainee/courses': typeof TraineeCoursesRoute
  '/trainee/feedback': typeof TraineeFeedbackRoute
  '/trainee/profile': typeof TraineeProfileRoute
  '/trainee/resource-viewer': typeof TraineeResourceViewerRoute
  '/trainee/results': typeof TraineeResultsRoute
  '/trainer/courses': typeof TrainerCoursesRoute
  '/trainer/library': typeof TrainerLibraryRoute
  '/trainer/profile': typeof TrainerProfileRoute
  '/trainer/questionnaires': typeof TrainerQuestionnairesRoute
  '/trainer/trainees': typeof TrainerTraineesRoute
  '/admin': typeof AdminIndexRoute
  '/trainee': typeof TraineeIndexRoute
  '/trainer': typeof TrainerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/competency': typeof AdminCompetencyRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/users': typeof AdminUsersRoute
  '/trainee/assessment': typeof TraineeAssessmentRoute
  '/trainee/catalog': typeof TraineeCatalogRoute
  '/trainee/certificates': typeof TraineeCertificatesRoute
  '/trainee/courses': typeof TraineeCoursesRoute
  '/trainee/feedback': typeof TraineeFeedbackRoute
  '/trainee/profile': typeof TraineeProfileRoute
  '/trainee/resource-viewer': typeof TraineeResourceViewerRoute
  '/trainee/results': typeof TraineeResultsRoute
  '/trainer/courses': typeof TrainerCoursesRoute
  '/trainer/library': typeof TrainerLibraryRoute
  '/trainer/profile': typeof TrainerProfileRoute
  '/trainer/questionnaires': typeof TrainerQuestionnairesRoute
  '/trainer/trainees': typeof TrainerTraineesRoute
  '/admin/': typeof AdminIndexRoute
  '/trainee/': typeof TraineeIndexRoute
  '/trainer/': typeof TrainerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/admin/announcements'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/competency'
    | '/admin/courses'
    | '/admin/users'
    | '/trainee/assessment'
    | '/trainee/catalog'
    | '/trainee/certificates'
    | '/trainee/courses'
    | '/trainee/feedback'
    | '/trainee/profile'
    | '/trainee/resource-viewer'
    | '/trainee/results'
    | '/trainer/courses'
    | '/trainer/library'
    | '/trainer/profile'
    | '/trainer/questionnaires'
    | '/trainer/trainees'
    | '/admin/'
    | '/trainee/'
    | '/trainer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/admin/announcements'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/competency'
    | '/admin/courses'
    | '/admin/users'
    | '/trainee/assessment'
    | '/trainee/catalog'
    | '/trainee/certificates'
    | '/trainee/courses'
    | '/trainee/feedback'
    | '/trainee/profile'
    | '/trainee/resource-viewer'
    | '/trainee/results'
    | '/trainer/courses'
    | '/trainer/library'
    | '/trainer/profile'
    | '/trainer/questionnaires'
    | '/trainer/trainees'
    | '/admin'
    | '/trainee'
    | '/trainer'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/admin/announcements'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/competency'
    | '/admin/courses'
    | '/admin/users'
    | '/trainee/assessment'
    | '/trainee/catalog'
    | '/trainee/certificates'
    | '/trainee/courses'
    | '/trainee/feedback'
    | '/trainee/profile'
    | '/trainee/resource-viewer'
    | '/trainee/results'
    | '/trainer/courses'
    | '/trainer/library'
    | '/trainer/profile'
    | '/trainer/questionnaires'
    | '/trainer/trainees'
    | '/admin/'
    | '/trainee/'
    | '/trainer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminCompetencyRoute: typeof AdminCompetencyRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  TraineeAssessmentRoute: typeof TraineeAssessmentRoute
  TraineeCatalogRoute: typeof TraineeCatalogRoute
  TraineeCertificatesRoute: typeof TraineeCertificatesRoute
  TraineeCoursesRoute: typeof TraineeCoursesRoute
  TraineeFeedbackRoute: typeof TraineeFeedbackRoute
  TraineeProfileRoute: typeof TraineeProfileRoute
  TraineeResourceViewerRoute: typeof TraineeResourceViewerRoute
  TraineeResultsRoute: typeof TraineeResultsRoute
  TrainerCoursesRoute: typeof TrainerCoursesRoute
  TrainerLibraryRoute: typeof TrainerLibraryRoute
  TrainerProfileRoute: typeof TrainerProfileRoute
  TrainerQuestionnairesRoute: typeof TrainerQuestionnairesRoute
  TrainerTraineesRoute: typeof TrainerTraineesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  TraineeIndexRoute: typeof TraineeIndexRoute
  TrainerIndexRoute: typeof TrainerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/admin/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/competency': {
      id: '/admin/competency'
      path: '/admin/competency'
      fullPath: '/admin/competency'
      preLoaderRoute: typeof AdminCompetencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainee/': {
      id: '/trainee/'
      path: '/trainee'
      fullPath: '/trainee/'
      preLoaderRoute: typeof TraineeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainee/assessment': {
      id: '/trainee/assessment'
      path: '/trainee/assessment'
      fullPath: '/trainee/assessment'
      preLoaderRoute: typeof TraineeAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainee/catalog': {
      id: '/trainee/catalog'
      path: '/trainee/catalog'
      fullPath: '/trainee/catalog'
      preLoaderRoute: typeof TraineeCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainee/certificates': {
      id: '/trainee/certificates'
      path: '/trainee/certificates'
      fullPath: '/trainee/certificates'
      preLoaderRoute: typeof TraineeCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainee/courses': {
      id: '/trainee/courses'
      path: '/trainee/courses'
      fullPath: '/trainee/courses'
      preLoaderRoute: typeof TraineeCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainee/feedback': {
      id: '/trainee/feedback'
      path: '/trainee/feedback'
      fullPath: '/trainee/feedback'
      preLoaderRoute: typeof TraineeFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainee/profile': {
      id: '/trainee/profile'
      path: '/trainee/profile'
      fullPath: '/trainee/profile'
      preLoaderRoute: typeof TraineeProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainee/resource-viewer': {
      id: '/trainee/resource-viewer'
      path: '/trainee/resource-viewer'
      fullPath: '/trainee/resource-viewer'
      preLoaderRoute: typeof TraineeResourceViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainee/results': {
      id: '/trainee/results'
      path: '/trainee/results'
      fullPath: '/trainee/results'
      preLoaderRoute: typeof TraineeResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/': {
      id: '/trainer/'
      path: '/trainer'
      fullPath: '/trainer/'
      preLoaderRoute: typeof TrainerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/courses': {
      id: '/trainer/courses'
      path: '/trainer/courses'
      fullPath: '/trainer/courses'
      preLoaderRoute: typeof TrainerCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/library': {
      id: '/trainer/library'
      path: '/trainer/library'
      fullPath: '/trainer/library'
      preLoaderRoute: typeof TrainerLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/profile': {
      id: '/trainer/profile'
      path: '/trainer/profile'
      fullPath: '/trainer/profile'
      preLoaderRoute: typeof TrainerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/questionnaires': {
      id: '/trainer/questionnaires'
      path: '/trainer/questionnaires'
      fullPath: '/trainer/questionnaires'
      preLoaderRoute: typeof TrainerQuestionnairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/trainees': {
      id: '/trainer/trainees'
      path: '/trainer/trainees'
      fullPath: '/trainer/trainees'
      preLoaderRoute: typeof TrainerTraineesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminCompetencyRoute: AdminCompetencyRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminUsersRoute: AdminUsersRoute,
  TraineeAssessmentRoute: TraineeAssessmentRoute,
  TraineeCatalogRoute: TraineeCatalogRoute,
  TraineeCertificatesRoute: TraineeCertificatesRoute,
  TraineeCoursesRoute: TraineeCoursesRoute,
  TraineeFeedbackRoute: TraineeFeedbackRoute,
  TraineeProfileRoute: TraineeProfileRoute,
  TraineeResourceViewerRoute: TraineeResourceViewerRoute,
  TraineeResultsRoute: TraineeResultsRoute,
  TrainerCoursesRoute: TrainerCoursesRoute,
  TrainerLibraryRoute: TrainerLibraryRoute,
  TrainerProfileRoute: TrainerProfileRoute,
  TrainerQuestionnairesRoute: TrainerQuestionnairesRoute,
  TrainerTraineesRoute: TrainerTraineesRoute,
  AdminIndexRoute: AdminIndexRoute,
  TraineeIndexRoute: TraineeIndexRoute,
  TrainerIndexRoute: TrainerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
